quarkus:
  application:
    name: user-management-service
  http:
    port: 8081
    root-path: /oms/user-management-service/

  datasource:
    db-kind: postgresql
    username: postgres
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5432/app_adaptor
      max-size: 20

  hibernate-orm:
    database:
      generation: update


  smallrye-openapi:
    path: /openapi
  swagger-ui:
      always-include: true
      path: /oms/user-management-service/swagger-ui
  smallrye-jwt:
    enabled: true

  cache:
    enabled: true
    caffeine:
      "user-user":
        expire-after-write: 10M
        maximum-size: 1000
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: oms-quarkus
smallrye:
  jwt:
    sign:
      key:
        location: 'privateKey.pem'
  log:
    category:
      "org.portfolio.giry.oms":
        level: DEBUG
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      level: INFO